// Anexo I do RDCBMERJ - 129 itens de tipificação
export interface ItemTipificacao {
  id: number;
  text: string;
}

export const ITENS_TIPIFICACAO: ItemTipificacao[] = [
  { id: 1, text: "Faltar à verdade." },
  { id: 2, text: "Utilizar-se do anonimato." },
  { id: 3, text: "Concorrer para a discórdia ou desarmonia ou cultivar inimizade entre camaradas." },
  { id: 4, text: "Freqüentar ou fazer parte de sindicatos, associações profissionais com caráter de sindicatos ou similares." },
  { id: 5, text: "Deixar de punir transgressor da disciplina." },
  { id: 6, text: "Não levar falta ou irregularidade que presenciar, ou de que tiver ciência e não lhe couber reprimir, ao conhecimento da autoridade competente, no mais curto prazo." },
  { id: 7, text: "Deixar de cumprir ou fazer cumprir normas regulamentares na esfera de suas atribuições." },
  { id: 8, text: "Deixar de comunicar a tempo, ao superior imediato, ocorrência no âmbito de suas atribuições quando se julgar suspeito ou impedido de providenciar a respeito." },
  { id: 9, text: "Deixar de comunicar ao superior imediato ou na ausência deste, a qualquer autoridade superior, toda informação que tiver sobre iminente perturbação da ordem pública ou grave alteração do serviço, logo que disto tenha conhecimento." },
  { id: 10, text: "Deixar de informar processo que lhe for encaminhado, exceto nos casos de suspeição ou impedimento ou absoluta falta de elementos, hipóteses em que estas circunstâncias serão fundamentadas." },
  { id: 11, text: "Deixar de encaminhar à autoridade competente, na linha de subordinação e no mais curto prazo, recurso ou documento que receber, desde que elaborado de acordo com os preceitos regulamentares, se não estiver na sua alçada dar solução." },
  { id: 12, text: "Retardar ou prejudicar medidas ou ações de ordem judicial ou policial de que esteja investido ou que deva promover." },
  { id: 13, text: "Apresentar parte ou recurso sem seguir as normas e preceitos regulamentares ou em termos desrespeitosos ou com argumentos falsos ou de ma fé, ou mesmo sem justa causa ou razão." },
  { id: 14, text: "Dificultar ao subordinado a apresentação de recursos." },
  { id: 15, text: "Deixar de comunicar ao superior a execução de ordem recebida, tão logo seja possível." },
  { id: 16, text: "Retardar a execução de qualquer ordem." },
  { id: 17, text: "Aconselhar ou concorrer para não ser cumprida qualquer ordem de autoridade competente, ou para retardar a sua execução." },
  { id: 18, text: "Não cumprir ordem recebida." },
  { id: 19, text: "Simular doença para esquivar-se ao cumprimento de qualquer dever de bombeiro-militar." },
  { id: 20, text: "Trabalhar mal, intencionalmente ou por falta de atenção em qualquer serviço ou instrução." },
  { id: 21, text: "Deixar de participar a tempo, à autoridade imediatamente superior, impossibilidade de comparecer à OBM ou a qualquer ato de serviço." },
  { id: 22, text: "Faltar ou chegar atrasado a qualquer ato de serviço em que deva tomar parte ou assistir." },
  { id: 23, text: "Permutar serviço sem permissão de autoridade competente." },
  { id: 24, text: "Comparecer o bombeiro-militar a qualquer solenidade, festividade ou reunião social, com uniforme diferente do previsto." },
  { id: 25, text: "Abandonar serviço para o qual tenha sido designado." },
  { id: 26, text: "Afastar-se de qualquer lugar em que deva estar por força de disposição legal ou ordem." },
  { id: 27, text: "Deixar de apresentar-se, nos prazos regulamentares, à OBM para que tenha sido transferido ou classificado e às autoridades competentes, nos casos de comissão ou serviço extraordinário para os quais tenha sido designado." },
  { id: 28, text: "Não se apresentar ao fim de qualquer afastamento do serviço ou, ainda, logo que souber que o mesmo foi interrompido." },
  { id: 29, text: "Representar a OBM e mesmo a Corporação, em qualquer ato, sem estar devidamente autorizado." },
  { id: 30, text: "Tomar compromisso pela OBM que comanda ou em que serve sem estar autorizado." },
  { id: 31, text: "Contrair dívida ou assumir compromisso superior às suas possibilidades, comprometendo o bom nome da classe." },
  { id: 32, text: "Esquivar-se a satisfazer compromisso de ordem moral ou pecuniária que houver assumido." },
  { id: 33, text: "Não atender a observação de autoridade competente, para satisfazer débito já reclamado." },
  { id: 34, text: "Não atender à obrigação de dar assistência a sua família ou dependente legalmente constituído." },
  { id: 35, text: "Fazer, diretamente ou por intermédio de outrem, transações pecuniária envolvendo assunto de serviço, bens da Administração Pública ou material proibido, quando isso não configure crime." },
  { id: 36, text: "Realizar ou propor transações pecuniárias envolvendo superior, igual ou subordinado. Não são considerados transações pecuniárias os empréstimos em dinheiro sem auferir lucro." },
  { id: 37, text: "Deixar de providenciar, a tempo, na esfera de suas atribuições, por negligência ou incúria, medidas contra qualquer irregularidade de que venha a tomar conhecimento." },
  { id: 38, text: "Recorrer ao Judiciário sem antes esgotar todos os recursos administrativos." },
  { id: 39, text: "Retirar ou tentar retirar de qualquer lugar sob a jurisdição de bombeiro-militar, material, viatura ou objeto ou mesmo deles servir-se, sem ordem do responsável ou proprietário." },
  { id: 40, text: "Não zelar devidamente, danificar ou extraviar, por negligência ou desobediência a normas de serviço, material da Fazenda Nacional, Estadual ou Municipal que esteja ou não sob sua responsabilidade direta." },
  { id: 41, text: "Ter pouco cuidado com o asseio próprio ou coletivo, em qualquer circunstância." },
  { id: 42, text: "Portar-se sem compostura em lugar público." },
  { id: 43, text: "Freqüentar lugares incompatíveis com o seu nível social e o decoro da classe." },
  { id: 44, text: "Permanecer a praça em dependência da OBM, desde que seja estranho ao serviço, ou sem consentimento ou ordem de autoridade competente." },
  { id: 45, text: "Portar a praça arma regulamentar sem estar de serviço ou sem ordem para tal." },
  { id: 46, text: "Portar a praça arma não regulamentar sem permissão por escrito de autoridade competente." },
  { id: 47, text: "Disparar arma com imprudência ou negligência." },
  { id: 48, text: "Içar ou arriar bandeira ou insígnia, sem ordem para tal." },
  { id: 49, text: "Dar toques ou fazer sinais, sem ordem para tal." },
  { id: 50, text: "Conversar ou fazer ruídos em ocasiões, lugares ou horas impróprias." },
  { id: 51, text: "Espalhar boatos ou notícias tendenciosas." },
  { id: 52, text: "Provocar ou fazer-se causa, voluntariamente, de origem de alarme injustificável" },
  { id: 53, text: "Usar violência desnecessária no ato de efetuar prisão." },
  { id: 54, text: "Maltratar preso sob sua guarda." },
  { id: 55, text: "Deixar alguém conversar ou entender-se com preso incomunicável, sem autorização de autoridade competente." },
  { id: 56, text: "Conversar com sentinela ou preso incomunicável." },
  { id: 57, text: "Deixar que preso conservam em seu poder instrumentos ou objetos não permitidos." },
  { id: 58, text: "Conversar, sentar-se ou fumar a sentinela ou o plantão da hora, ou ainda, consentir na formação ou permanência de grupo ou de pessoa junto ao seu posto de serviço." },
  { id: 59, text: "Fumar em local de incêndio e em lugares ou ocasiões onde isso seja vedado, ou quando se dirigir a superior." },
  { id: 60, text: "Tomar parte em jogos proibidos ou jogar a dinheiro os permitidos, em área de bombeiro-militar ou sob jurisdição de bombeiro-militar." },
  { id: 61, text: "Tomar parte, em área de bombeiro-militar ou sob jurisdição de bombeiro-militar, em discussões a respeito de política ou religião, ou mesmo provocá-la." },
  { id: 62, text: "Manifestar-se, publicamente, a respeito de assuntos políticos ou tomar parte, fardado, em manifestações da mesma natureza." },
  { id: 63, text: "Deixar o superior de determinar a saída imediata, de solenidade de bombeiro-militar ou civil, de subordinado que a ela compareça em uniforme diferente do previsto." },
  { id: 64, text: "Apresentar-se desuniformizado, mal uniformizado ou com o uniforme alterado." },
  { id: 65, text: "Sobrepor ao uniforme insígnia ou medalha não regulamentar, bem como, indevidamente distintivo e condecoração." },
  { id: 66, text: "Andar o bombeiro-militar a pé ou em coletivos públicos com o uniforme inadequado contrariando o RUCBERJ ou normas a respeito." },
  { id: 67, text: "Usar trajes civil, o cabo ou soldado, quando isso contrariar ordem de autoridade competente." },
  { id: 68, text: "Ser indiscreto em relação a assuntos de caráter oficial cuja divulgação possa ser prejudicial à disciplina ou à boa ordem do serviço." },
  { id: 69, text: "Dar conhecimento de fatos, documentos ou assuntos de bombeiros-militares a quem deles não deva ter conhecimento e não tenha atribuições para nele intervir." },
  { id: 70, text: "Publicar ou contribuir para que sejam publicados fatos, documentos ou assuntos de bombeiros-militares que possam concorrer para o desprestígio da Corporação ou firam a disciplina ou a segurança." },
  { id: 71, text: "Entrar ou sair de qualquer OBM, o cabo ou soldado, com objetos ou embrulhos, sem autorização do comandante da guarda ou autorização similar." },
  { id: 72, text: "Deixar o oficial BM ou aspirante-a-oficial BM ao entrar em OBM onde não sirva, de dar ciência de sua presença ao oficial de dia e, em seguida, de procurar o comandante ou o mais graduado dos oficiais BM presentes, para cumprimentá-lo." },
  { id: 73, text: "Deixar o subtenente, sargento, cabo ou soldado BM, ao entrar em OBM onde não sirva, de apresentar-se ao oficial de dia ou seu substituto legal." },
  { id: 74, text: "Deixar o comandante da guarda ou agente de segurança correspondente de cumprir as prescrições regulamentares com respeito à entrada ou à permanência na OBM de civis, militares ou bombeiros-militares estranhos à mesma." },
  { id: 75, text: "Penetrar o bombeiro-militar, sem permissão ou ordem, em aposentos destinados a superior ou onde esse se ache, bem como, em qualquer lugar onde a entrada lhe seja vedada." },
  { id: 76, text: "Penetrar ou tentar penetrar o bombeiro-militar em alojamento de outra OBM, depois da revista do recolher, salvo os oficiais ou sargentos, que, pelas suas funções, sejam a isto obrigado." },
  { id: 77, text: "Entrar ou sair de OBM com força armada, sem prévio conhecimento ou ordem da autoridade competente." },
  { id: 78, text: "Abrir ou tentar abrir qualquer dependência da OBM fora das horas de expediente, desde que não seja respectivo chefe ou sem a sua ordem escrita com a expressa declaração de motivo, salvo situações de emergência." },
  { id: 79, text: "Desrespeitar regras de trânsito, medidas gerais de ordem policial, judicial ou administrativa." },
  { id: 80, text: "Deixar de portar, o bombeiro-militar, o seu documento de identidade, estando ou não fardado ou de exibi-la quando solicitado." },
  { id: 81, text: "Maltratar ou não ter o devido cuidado no trato com os animais." },
  { id: 82, text: "Desrespeitar em público as convenções sociais." },
  { id: 83, text: "Desconsiderar ou desrespeitar a autoridade civil." },
  { id: 84, text: "Desrespeitar corporação judiciária, ou qualquer de seus membros, bem como criticar, em público ou pela imprensa, seus atos e decisões." },
  { id: 85, text: "Não se apresentar a superior hierárquico ou de sua presença retirar-se, sem obediência às normas regulamentares." },
  { id: 86, text: "Deixar, quando estiver sentado, de oferecer seu lugar a superior, ressalvadas as exceções previstas no Regulamento de Continências, Honras e Sinais de Respeito das Forças Armadas." },
  { id: 87, text: "Sentar-se a praça, em público, à mesa em que estiver oficial ou vice-versa, salvo em solenidade, festividade ou reuniões sociais." },
  { id: 88, text: "Deixar, deliberadamente, de corresponder a cumprimento de subordinado." },
  { id: 89, text: "Deixar o subordinado, quer uniformizado, quer em traje civil, de cumprimentar superior, uniformizado ou não, neste caso desde que o conheça, ou prestar-lhe as homenagens e sinais regulamentares de consideração e respeito." },
  { id: 90, text: "Deixar ou negar-se a receber vencimento, alimentação, fardamento, equipamento ou material que lhe seja destinado ou deva ficar em seu poder ou sob sua responsabilidade." },
  { id: 91, text: "Deixar o bombeiro-militar, presente a solenidades internas ou externas onde se encontrem superiores hierárquicos, de saudá-los de acordo com as normas regulamentares." },
  { id: 92, text: "Deixar o oficial BM ou aspirante-a-oficial BM, tão logo seus afazeres o permitam, de apresentar-se ao de maior posto e ao substituto legal imediato, da OBM onde serve, para cumprimentá-lo, salvo ordem ou instrução a respeito." },
  { id: 93, text: "Deixar o subtenente BM ou o sargento BM, tão logo seus afazeres o permitam, de apresentar-se ao seu comandante ou chefe imediato." },
  { id: 94, text: "Dirigir-se, referir-se ou responder de maneira desatenciosa a superior." },
  { id: 95, text: "Censurar ato de superior ou procurar desconsiderá-lo." },
  { id: 96, text: "Procurar desacreditar seu igual ou subordinado." },
  { id: 97, text: "Ofender, provocar ou desafiar superior." },
  { id: 98, text: "Ofender, provocar ou desfiar seu igual ou subordinado." },
  { id: 99, text: "Ofender a moral por atos, gestos ou palavras." },
  { id: 100, text: "Travar discussão, rixa ou luta corporal com seu igual ou subordinado." },
  { id: 101, text: "Discutir ou provocar discussões, por qualquer veículo de comunicação, sobre assuntos políticos, militares ou de bombeiro-militar, excetuando-se os de natureza exclusivamente técnica, quando devidamente autorizado." },
  { id: 102, text: "Autorizar, promover ou tomar parte em qualquer manifestação coletiva, seja de caráter reivindicatório, seja de crítica ou de apoio a ato superior, com exceção das demonstrações íntimas de boa e sã camaradagem e com conhecimento do homenageado." },
  { id: 103, text: "Aceitar o bombeiro-militar qualquer manifestação coletiva de seus subordinados, salvo a exceção do número anterior." },
  { id: 104, text: "Autorizar, promover ou assinar petições coletivas dirigidas a qualquer autoridade civil ou bombeiro-militar." },
  { id: 105, text: "Dirigir memoriais ou petições, a qualquer autoridade, sobre assuntos de alçada do Comando-Geral do CBERJ, salvo em grau de recurso, na forma prevista neste Regulamento." },
  { id: 106, text: "Ter em seu poder, introduzir ou distribuir, em área de bombeiro-militar ou sob a jurisdição de bombeiro-militar publicações, estampas ou jornais que atentem contra disciplina ou a moral." },
  { id: 107, text: "Ter em seu poder ou introduzir, em área de bombeiro-militar ou sob a jurisdição de bombeiro-militar, inflamável ou explosivo, sem permissão da autoridade competente." },
  { id: 108, text: "Ter em seu poder, introduzir ou distribuir, em área de bombeiro-militar ou sob a jurisdição de bombeiro-militar, tóxicos, ou entorpecentes, a não ser mediante prescrição de autoridade competente." },
  { id: 109, text: "Ter em seu poder ou introduzir, em área de bombeiro-militar ou sob jurisdição de bombeiro-militar, bebidas alcoólicas, salvo quando devidamente autorizado." },
  { id: 110, text: "Fazer uso, estar sob ação ou introduzir outrem a uso de tóxicos, entorpecentes ou produtos alucinógenos." },
  { id: 111, text: "Embriagar-se ou induzir outro à embriaguez, embora tal estado não tenha sido constatado por médico." },
  { id: 112, text: "Usar o uniforme, quando de folga, se isso contrariar ordem de autoridade competente." },
  { id: 113, text: "Usar, quando uniformizado, barba, cabelos, bigode ou costeletas excessivamente comprido ou exagerados, contrariando disposições a respeito." },
  { id: 114, text: "Utilizar ou autorizar a utilização dos subordinados para serviços não previstos em regulamento." },
  { id: 115, text: "Dar por escrito ou verbalmente, ordem ilegal ou claramente inexeqüível, que possa acarretar ao subordinado responsabilidade, ainda que não chegue a ser comprida." },
  { id: 116, text: "Prestar informação a superior induzindo-o a erro deliberada ou intencionalmente." },
  { id: 117, text: "Omitir, em nota de ocorrência, relatório ou qualquer documento, dados indispensáveis ao esclarecimento dos fatos." },
  { id: 118, text: "Violar ou Deixar de preservar local de crime." },
  { id: 119, text: "Soltar preso ou detido ou dispensar parte de ocorrência sem ordem de autoridade competente." },
  { id: 120, text: "Participar o bombeiro-militar da ativa, de firma comercial, de emprego industrial de qualquer natureza, ou nelas exercer função ou emprego remunerado, salvo como acionista ou quotista em sociedade anônima ou por cotas de responsabilidade limitada." },
  { id: 121, text: "Transportar em viatura ou viaturas de que é responsável pessoas estranhas sem permissão da autoridade competente, salvo quando a comprovada natureza do serviço assim o exigir." },
  { id: 122, text: "Não observar as ordens em vigor relativas ao tráfego nas saídas e regressos de socorros, bem como nos deslocamentos de viaturas nas imediações e interior dos quartéis, quando não estiverem em serviço de socorros." },
  { id: 123, text: "Executar exercícios profissionais que envolvam acentuados perigos, sem autorização superior, salvos nos casos de competições, demonstrações, etc., em que haverá um responsável." },
  { id: 124, text: "Afastar-se do local de incêndio, desabamento, inundação ou outro qualquer serviço de socorro, sem estar autorizado." },
  { id: 125, text: "Afastar-se o motorista da viatura sob sua responsabilidade, nos serviços de incêndio e outros misteres da profissão." },
  { id: 126, text: "Não dar ciência à Administração dos avisos de incêndio de regular ou grande proporções que tenha recebido e nos quais haja socorro empenhado." },
  { id: 127, text: "Faltar à corrida para incêndio ou outros socorros." },
  { id: 128, text: "Receber ou permitir que seu subordinado receba, em local de socorro, quaisquer objetos ou valores, mesmo quando doados pelo proprietário ou responsável pelo local dos sinistro." },
  { id: 129, text: "Afastar-se o oficial BM de sua residência quando nela deva permanecer por motivo de serviço ou punição." }
];

// Função auxiliar para buscar item por número
export function buscarItemPorNumero(numero: number): ItemTipificacao | undefined {
  return ITENS_TIPIFICACAO.find(item => item.id === numero);
}

// Função auxiliar para buscar itens por texto
export function buscarItensPorTexto(texto: string): ItemTipificacao[] {
  const termoLower = texto.toLowerCase();
  return ITENS_TIPIFICACAO.filter(item =>
    item.id.toString().includes(texto) ||
    item.text.toLowerCase().includes(termoLower)
  );
}
